services:
  dev:
    image: hugomods/hugo:exts
    working_dir: /src
    volumes:
      - .:/src
    ports:
      - "1313:1313"
    command: hugo server -D --bind 0.0.0.0 --poll 500ms

  prod:
    build: .
    ports:
      - "28080:80"
